import React,{useEffect,useState} from 'react'
import {createRoot} from 'react-dom/client'
import SumoTwin from './SumoTwin.jsx'
import './styles.css'

const API=(import.meta.env.VITE_API_URL||'http://localhost:8000').replace(/\/$/,'')
const Metric=({label,value,hint})=><div className="metric"><span>{label}</span><strong>{value}</strong>{hint&&<small>{hint}</small>}</div>
const phaseLabel=p=>p==='NS'?'N/S GREEN':p==='EW'?'E/W GREEN':p==='AMBER'?'AMBER':'—'

function Next({label,frame,smart}){const j=frame?.junction_b||{};return <div className={`next-card ${smart?'smart-next':''}`}><div className="next-head"><div><strong>{label}</strong><span>Junction B · 180 m downstream</span></div><b>{phaseLabel(j.phase)}</b></div><div className="mini-junction"><div className="mini-road vertical"/><div className="mini-road horizontal"/><div className="mini-center">B</div><span className="mini-q north">N {j.north||0}</span><span className="mini-q south">S {j.south||0}</span><span className="mini-q east">E {j.east||0}</span><span className="mini-q west">W {j.west||0}</span></div><div className="next-stats"><span><b>{j.total_queue||0}</b> queue</span><span><b>{frame?.vehicles?.length||0}</b> network vehicles</span><span><b>{frame?.throughput||0}</b> completed trips</span></div></div>}

function App(){
 const[data,setData]=useState(null),[tick,setTick]=useState(0),[running,setRunning]=useState(false),[view,setView]=useState('bird'),[speed,setSpeed]=useState(1),[scenario,setScenario]=useState('north-surge'),[error,setError]=useState(''),[loading,setLoading]=useState(false)
 const load=async()=>{setLoading(true);setRunning(false);setError('');try{const r=await fetch(`${API}/api/physics/comparison?steps=100&seed=7&scenario=${scenario}`);const text=await r.text();if(!r.ok)throw new Error(text||`HTTP ${r.status}`);const p=JSON.parse(text);setData(p);setTick(0)}catch(e){setData(null);setError(`SUMO physics unavailable. Install SUMO + netconvert and ensure both are on PATH, then restart FastAPI. ${e.message}`)}finally{setLoading(false)}}
 useEffect(()=>{load()},[scenario])
 useEffect(()=>{if(!running||!data)return;const id=setInterval(()=>setTick(t=>t>=data.steps-1?0:t+1),Math.max(90,650/speed));return()=>clearInterval(id)},[running,data,speed])
 const fixed=data?.fixed.frames?.[tick],smart=data?.adaptive.frames?.[tick],fs=data?.fixed.summary,ss=data?.adaptive.summary
 const q=fs&&ss&&fs.average_queue?Math.round((1-ss.average_queue/fs.average_queue)*100):0
 const w=fs&&ss&&fs.average_wait_per_tick?Math.round((1-ss.average_wait_per_tick/fs.average_wait_per_tick)*100):0
 const th=fs&&ss&&fs.throughput?Math.round((ss.throughput/fs.throughput-1)*100):0
 return <main>
  <header className="hero"><div><p className="eyebrow">SIH PS90 · SUMO PHYSICS DIGITAL TWIN</p><h1>Same demand. Real vehicle physics. Two signal policies.</h1><p className="sub">Both sides are separate SUMO runs with the same seed and insertion schedule. IDM controls car-following, LC2013 controls lane changing, and the browser only replays TraCI positions, angles, speeds and lanes.</p></div><div className="hero-status">{loading?'RUNNING SUMO…':error?'PHYSICS OFFLINE':'SUMO / TRACI'}</div></header>
  <div className="controls"><button onClick={()=>setRunning(x=>!x)} disabled={!data||loading}>{running?'⏸ Pause':'▶ Replay comparison'}</button><button onClick={()=>{setTick(0);setRunning(false)}}>Reset</button><button onClick={()=>setView(v=>v==='bird'?'pov':'bird')}>{view==='bird'?'Intersection POV':'Bird’s-eye A → B'}</button><button onClick={load} disabled={loading}>{loading?'Simulating…':'Re-run SUMO'}</button><label>Traffic pattern<select value={scenario} onChange={e=>setScenario(e.target.value)}><option value="north-surge">N/S rush surge</option><option value="east-surge">E/W rush surge</option><option value="balanced">Balanced traffic</option></select></label><label>Replay speed<select value={speed} onChange={e=>setSpeed(Number(e.target.value))}><option value="1">1×</option><option value="2">2×</option><option value="4">4×</option></select></label></div>
  {error&&<div className="error-box">{error}<br/><br/><code>sumo --version</code> and <code>netconvert --version</code> must both work in the terminal that starts FastAPI.</div>}
  {data&&<><div className="comparison-grid"><SumoTwin frame={fixed} mode={view} title="Fixed Clock · SUMO" accent="baseline"/><SumoTwin frame={smart} mode={view} title="SmartTraffic PQP · SUMO" accent="smart"/></div><div className="timeline"><span>T+{tick}s</span><input type="range" min="0" max={data.steps-1} value={tick} onChange={e=>setTick(Number(e.target.value))}/><span>{data.steps}s</span></div><div className="metric-grid"><Metric label="Average queue reduction" value={`${q}%`} hint="SUMO PQP vs fixed"/><Metric label="Average wait reduction" value={`${w}%`} hint="same demand seed"/><Metric label="Throughput change" value={`${th>=0?'+':''}${th}%`} hint="completed SUMO trips"/><Metric label="Junction B peak queue" value={`${fs?.junction_b_peak_queue||0} → ${ss?.junction_b_peak_queue||0}`} hint="fixed → PQP upstream"/></div><section className="corridor-panel"><p className="eyebrow">DOWNSTREAM PROPAGATION</p><h2>The next junction is part of the same physical SUMO network</h2><div className="next-grid"><Next label="Fixed corridor" frame={fixed}/><Next label="SmartTraffic corridor" frame={smart} smart/></div></section><section className="algorithm-panel"><p className="eyebrow">PHYSICS + CONTROL</p><h2>What is actually running</h2><div className="algo-grid"><div><strong>IDM car-following</strong><p>SUMO determines acceleration, braking and following gaps.</p></div><div><strong>LC2013 lane changing</strong><p>SUMO decides lane changes; the browser does not script them.</p></div><div><strong>Mixed vehicle dynamics</strong><p>Cars, bikes, autos, buses, trucks and vans use different dimensions and dynamics.</p></div><div><strong>PQP signal control</strong><p>Queue + 0.8 × positive queue growth, with minimum/maximum green protection.</p></div></div><p className="algo-note">The browser receives authoritative vehicle x/y position, angle, lane and speed from TraCI every one-second simulation step.</p></section></>}
 </main>
}
createRoot(document.getElementById('root')).render(<App/>)
